### ISSUE TITLE
Server crashes with gilded armor mod

### ISSUE THREAD

**Issue by WillouwCode** [MaroonShaded/GildedArmor#11]
Forge 1.17.1 - 37.0.71

error in output

java.util.concurrent.ExecutionException: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: #gildedarmor:enderite_chestplate
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:141) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.17.1-37.0.71.jar%2322!:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: #gildedarmor:enderite_chestplate
        at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:35) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.world.item.crafting.Ingredient.m_43919_(Ingredient.java:211) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[forge-1.17.1-37.0.71-universal.jar%2359!:?]
        at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[forge-1.17.1-37.0.71-universal.jar%2359!:?]
        at net.minecraft.world.item.crafting.Ingredient.m_43917_(Ingredient.java:183) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.world.item.crafting.UpgradeRecipe$Serializer.m_6729_(UpgradeRecipe.java:77) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.world.item.crafting.UpgradeRecipe$Serializer.m_6729_(UpgradeRecipe.java:75) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.world.item.crafting.RecipeManager.m_44045_(RecipeManager.java:143) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:59) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:36) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SourceFile:13) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SourceFile:71) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SourceFile:70) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SourceFile:71) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SourceFile:70) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SourceFile:71) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SourceFile:70) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143) ~[?:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance$1.m_10855_(SourceFile:53) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance$1.m_6769_(SourceFile:50) ~[server-1.17.1-20210706.113038-srg.jar%2355!:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]

**Comment by MaroonShaded** [comment]
I didn't see github sorry, I'll publish a new version with a fix asap
